name: biobb_wf_cmip
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==5.2.0
  - biobb_cmip==5.2.0
  - biobb_structure_utils==5.2.0
  - biobb_chemistry==5.2.0
  - biobb_amber==5.2.0
  - plotly
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
  - simpletraj
